name: Build main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@slalpha3
        env:
          CI_BUILD: true
        with:
          args:
            build --code-coverage
      - name: Build with Gradle  
        run: |
          set -e   
          bash <(curl -s https://codecov.io/bash)
