name: Build main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@slalpha3
        env:
          CI_BUILD: true
        with:
          args:
            build --code-coverage
      - name: Publish Code coverage
        run: |
          set -e   
          bash <(curl -s https://codecov.io/bash)
      - name: Integration Test with Kuberentes cluster
        run: |
          set -e 
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
          kind create cluster
          export KUBECONFIG="$(kind get kubeconfig-path)"
          kind load docker-image hello:v1.0.0
          kubectl apply -f target/kubernetes/hackathon
          sleep 60
          kubectl port-forward deployment/hackathon-deployment 9090:9090 &      
          echo "Executing curl command"
          # curl "http://127.0.0.1:9090/hello/sayHello" -v
              
